name: update plants

on:
  workflow_dispatch:
  schedule:
    - cron: '0 24 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: update
      run: make fetch_plants githubToken=${{ secrets.JPS_GITHUB_TOKEN }}